name: Build

on:
  push:
    branches:
      - '*'
      - 'caroline/fix-text-errors'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - run: make test