name: Publish php sdk

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Environment Variable
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Package
        run: |
          echo "<?php namespace SmartyStreets\PhpSdk;const VERSION = '${{ env.RELEASE_VERSION }}'" > src/Version.php
          VERSION=${{ env.RELEASE_VERSION }} make release
